server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://www.xinanzhiyi.com:3306/xiaomi?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: xinanzhiyi123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 49.234.233.235
    password: 123456
  rabbitmq:
    host: 49.234.233.235
    username: admin
    password: admin
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true